### ISSUE TITLE
Problem with ripple effect because of the position

### ISSUE THREAD

**Issue by robbix1206** [PolymerElements/paper-item#14] opened 2015-06-26 09:24 UTC
Polymer version : 1.0.1
The ripple effect affect all the parent content because the position of items is unset.
Example Code :
``` 
<paper-header-panel mode="waterfall">
    <paper-toolbar>
        <div class="appname">App name</div>
    </paper-toolbar>
    <paper-icon-item>
        <paper-ripple></paper-ripple>
        <iron-icon icon="home" item-icon></iron-icon>
        Home
    </paper-icon-item>
    <paper-icon-item>
        <paper-ripple></paper-ripple>
        <iron-icon icon="home" item-icon></iron-icon>
        Home
    </paper-icon-item>
</paper-header-panel>
``` 
All the paper header panel content is rippled but only the clicked item need to be rippled.

I fix it by myself but I think it will be better if that's already include in paper-item's css rules.

Fix it with "paper-icon-item{position: relative;}"
(Sorry for my English which is not very good)

**Comment by notwaldorf** [comment] 2015-10-26 18:25
I'm sorry, I can't repro this. Here's a jsbin with your code (http://jsbin.com/revunacipa/edit?html,output), but I don't see the icons appearing. Could you modify it, if this is still reproducible?

**Comment by robbix1206** [comment] 2015-10-26 20:30
The problem come from paper-ripple directly so I think they correct the
problem directly on it
Le 26 oct. 2015 19:25, "Monica Dinculescu" <notifications@github.com> a
écrit :

**Comment by notwaldorf** [comment] 2015-12-15 23:16
Closing, since this looks fixed

**Closed by notwaldorf** 2015-12-15 23:16 UTC
Labels: pending-response
