### ISSUE TITLE
Setting hidden attribute/property doesn't work in 1.1.0-1.1.1

### ISSUE THREAD

**Issue by mbochenek** [PolymerElements/paper-item#58] opened 2015-11-24 14:02 UTC
As the title says upgrading element to the newest version breaks showing/hiding the element.

**Comment by ebidel** [comment] 2015-11-24 16:11
Can you provide more details along with a jsbin that repos the issue?

**Comment by mbochenek** [comment] 2015-11-25 08:41
It works when:
html /deep/ [hidden] {
    display: none !important;
from iron-flex-layout/classes/iron-shadow-flex-layout.html is present.

**Comment by notwaldorf** [comment] 2015-11-25 18:13
I still don't understand what the problem is. Here is a JSBin where I am setting `hidden` on a `paper-item`, and it is, in fact, hidden: http://jsbin.com/qutema/edit?html,output

Does this not work on a specific browser? Unless you can provide us with a JSBin that repros your particular problem, provide a snippet of your code, or explain it in more details (i.e. exactly what is not hidden correctly), I'm afraid there isn't much we can do to help.

**Comment by mbochenek** [comment] 2015-11-26 10:05
I'm using Shadow DOM in android webview (chromium 46.0.2490.76). The issue affects also other elements in my custom element (paper-button for example).

Hiding works after adding:
` [hidden] {
    display: none !important;
  }` 
to the custom element style which includes paper-items.

I checked your code and it works too, this time style:
`[hidden] {
    display: none !important;
}` 
is applied from iron-flex-layout.

It also works using shady DOM and like above the style from iron-flex-layout is applied.

In every case 
`paper-button[Attributes Style] {
    display: none;
}`
is set but it is not applied because 
`:host {
  display: inline-block;
}
` and 
`:host {
  display: block;
        position: relative;
}` are present (and/or display: flex and -webkit-flex) - I don't know if it's the right track, though.

**Comment by notwaldorf** [comment] 2015-11-28 01:36
If you don't include `iron-flex-layout` correctly, you will not get the `hidden` style. Prior to the 1.1 release, `paper-item` was using a version of `iron-flex-layout` that was styling `hidden` using `/deep/` which means it was incorrectly making it available throughout your app. We have removed this, so in the particular custom element that is using `hidden`, you need to either import `iron-flex-layout` or define the `hidden` class yourself

**Comment by mbochenek** [comment] 2015-11-30 11:23
I'm aware of this, actually. I do import `iron-flex-layout` in the custom element and yet the `hidden` style from iron-flex-layout is not available. How do I import it correctly?

**Comment by mbochenek** [comment] 2015-12-02 16:27
There's another issue this time with `paper-dropdown-menu` scroll. I created a sample: 
http://jsbin.com/xelekaneso/edit?html,console,output
As you can see the scroll is not working - if you use shady DOM instead - it does.

**Comment by notwaldorf** [comment] 2015-12-02 19:36
@mbochenek I get a ""TypeError: Polymer is not a function at http://null.jsbin.com/runner:2:5"" in your JSBin, so I don't think anything is working.

Re: your `paper-item` issue, could you please provide me with a snippet of code, or a JSBin, and with details about exactly which element isn't being hidden? Without seeing what your DOM looks like, I can't understand what's going on. :(

**Comment by notwaldorf** [comment] 2015-12-02 19:52
Ok, I've updated your jsbin so that it actually works as a jsbin: http://jsbin.com/wakuno/edit?html,output
These things are hidden, and work as hidden on Chrome, Firefox, and Chrome 46.0.2490.76 on a Nexus 5 (this is the demo without the code: http://output.jsbin.com/wakuno)
- a standalone paper-item
- a paper-item inside a paper-listbox inside a paper-dropdown-menu
- an entire custom element

**Comment by notwaldorf** [comment] 2015-12-02 19:56
By looking at your initial JSBin, you're not including `webcomponentsjs/webcomponents-lite.js` anywhere, which might be a problem.

**Comment by notwaldorf** [comment] 2015-12-02 20:07
I've opened https://github.com/PolymerElements/paper-dropdown-menu/issues/92 for the scroll issue. Closing this, since there's no issue with `paper-item`

**Comment by mbochenek** [comment] 2015-12-03 09:21
Regarding the closed issue - check what style is being applied to the "batman" item.

**Comment by notwaldorf** [comment] 2015-12-03 22:17
That's because `paper-listbox` still includes the classes version. I have tested it on a version where I've just removed it (I'll send a PR in a second), and in that case, the style on the "Batman" element is:
<img width="532" alt="screen shot 2015-12-03 at 2 07 16 pm" src="https://cloud.githubusercontent.com/assets/1369170/11575909/58fc24a6-99c8-11e5-9854-a793aa1d84b8.png">
<img width="486" alt="screen shot 2015-12-03 at 2 14 53 pm" src="https://cloud.githubusercontent.com/assets/1369170/11575910/58ffd3bc-99c8-11e5-8657-fdaedf99d357.png">

And it is still hidden:
<img width="251" alt="screen shot 2015-12-03 at 2 17 22 pm" src="https://cloud.githubusercontent.com/assets/1369170/11575960/978d7094-99c8-11e5-92bc-4bebb7505c1e.png">

So that still does not reproduce your original problem.

**Comment by mbochenek** [comment] 2015-12-04 07:44
Consider this example (I changed paper-listbox to iron-selector):
http://jsbin.com/jenawanela/edit?html,output

**Comment by notwaldorf** [comment] 2015-12-04 19:37
Oh, interesting. I can repro this now, so re-opening.

**Comment by notwaldorf** [comment] 2015-12-04 21:50
Alright. After much investigation, this is actually a Chrome bug (:sob:): https://code.google.com/p/chromium/issues/detail?id=566168. Basically, the shadow DOM does the wrong thing, and gives the `hidden` attribute lower priority over the `display: block` style in the host.

I'm closing this bug again, since this needs to be fixed in Chrome, and there's nothing we can really do about it in the meantime :(

**Comment by mbochenek** [comment] 2015-12-07 08:16
You're welcome, I hope it gets fixed soon.

P.S.
Where should I send my bank account number?;)

**Comment by leozleung** [comment] 2015-12-09 01:32
it seems that it is not a chrome bug and they have closed the issue #556168.
<code>display: block</code> style on host has higher priority than <code>hidden</code> attribute, not just shadowDom, but html,
http://jsbin.com/kupetabipe/edit?html,output
https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute

**Comment by notwaldorf** [comment] 2015-12-09 18:32
I'm going to re-open this, and add a `hidden` style to `paper-item`. Basically, we've all been using `hidden` incorrectly, and assuming it will Do The Right Thing™️, which turns out is not how `hidden` works at all.

**Closed** 2015-12-09 21:31 UTC
