### ISSUE TITLE
paper-icon-item - clickable area in Firefox

### ISSUE THREAD

**Issue by bwh-rl** [PolymerElements/paper-item#36] opened 2015-10-21 14:31 UTC
In Firefox i got the problem that the first click on the text or the icon of an paper-icon-item highlights the item, but does not fire "tap", and the parent paper element does not get a "iron-select".

If the tap goes to a blank space of the paper-icon-item (where no child content like icon or text is present), events are fired. If the paper-icon-item is already highlighted, iron-select or tap get fired too.

This problem does not occur in chrome.

					<paper-menu on-iron-select="functionWithSomeConsole">

						<paper-icon-item on-tap="functionWithSomeConsole">
							<iron-icon icon="favorite" item-icon></iron-icon>
							<span>[[ someI18nDynamicTextBinding ]]</span>
						</paper-icon-item>

						<paper-icon-item on-tap="functionWithSomeConsole">
							<iron-icon icon="favorite" item-icon></iron-icon>
							<span>[[ someI18nDynamicTextBinding ]]</span>
						</paper-icon-item>

					</paper-menu>

**Comment by MartinMoizard** [comment] 2015-10-27 09:40
I noticed the same problem. +1.

**Comment by sbley** [comment] 2015-11-06 10:53
Is this a duplicate of https://github.com/PolymerElements/polymer-starter-kit/issues/166?

**Comment by notwaldorf** [comment] 2015-12-15 23:18
Do you have a jsbin reproducing this issue? Here's a sample one to get you started: http://jsbin.com/cagaye/edit?html,output

**Comment by bwh-rl** [comment] 2015-12-16 10:20
The problem occurs only on child elements.
The span tag was necessary for the data binding.
This would be possible via compound bindings now,
but the problem would still exist for the iron-icon.

http://jsbin.com/ciqituzaji/9/edit?html,output

**Comment by notwaldorf** [comment] 2016-01-30 01:36
This looks like it's a duplicate of https://github.com/PolymerElements/paper-item/issues/46, which was already fixed. Please re-open if that's not the case

**Closed by notwaldorf** 2016-01-30 01:36 UTC
Labels: pending-response
